### PR TITLE
#41 Add fromTriangles definition for ts.

### PR DESCRIPTION
**Pull request by SophiaLi1**

### CODE REVIEW

**Comment by chrvadala** [comment]
Thanks for this integration. Could you add also the smoothMatrix ts definition? I'll publish a patch version as soon it's ready.

**Comment by SophiaLi1** [comment]
Sure!

**Comment by SophiaLi1** [comment]
@chrvadala Any idea why the travis CI build failed and what I could improve?

**Comment by chrvadala** [comment]
Unfortunately it is an issue that I found also on some other open source projects. There's a bug with the coverage system. I added a message on their issue tracker and I hope that they'll fix it soon.
You can follow the conversation here https://github.com/lemurheavy/coveralls-public/issues/1264#issuecomment-464734002. Unfortunately we have to wait their fix.

**Comment by chrvadala** [comment]
It seems that coveralls fixed the issue. I've restarted the ci. It should pass now.

**Comment by SophiaLi1** [comment]
Sounds good!

**Comment by chrvadala** [comment]
Released on 1.15.1. Thanks

**Pull request merged**
